version: 2

updates:
  # PyPI updates for core dependencies
  - package-ecosystem: pip
    directory: "/ci"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "cartopy"
        versions: ["0.24.1"]
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Type: Maintenance"
      - "Area: Infrastructure"
    commit-message:
      prefix: "CI: "
      include: "scope"
    groups:
      coredeps:
        applies-to: version-updates
        update-types:
          - "patch"

  # PyPI updates for dev tools
  - package-ecosystem: pip
    directory: "/ci-dev"
    schedule:
      interval: weekly
    # We don't need to worry about updating to every patch release of dev tools
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Type: Maintenance"
      - "Area: Infrastructure"
    commit-message:
      prefix: "CI: "
      include: "scope"
    groups:
      flake8:
        patterns:
          - "flake8*"
          - "pycodestyle"
          - "pyflakes"

  # Update GitHub Actions versions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "-"
    labels:
      - "Type: Maintenance"
      - "Area: Infrastructure"
    commit-message:
      prefix: "CI: "
      include: "scope"
