codecov:
  notify:
    require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: '80'
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    project:
      default: false
      library:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
        paths:
          - "siphon/(\w+/)?[^/]+\.py$"

      tests:
        target: 100%
        paths: "siphon/.*/tests/.*"

  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/0eb95be6d20af5b9a4f0"

comment: off
