name: Unstable Builds

on:
  workflow_call:
    outputs:
      tests_result:
        description: "Result from running tests"
        value: ${{ jobs.Tests.outputs.result }}
      docs_result:
        description: "Result from running docs"
        value: ${{ jobs.Docs.outputs.result }}

jobs:
  Tests:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.tests.outcome }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        fetch-depth: 150
        fetch-tags: true

    - name: Assemble test requirements
      run: |
        echo git+https://github.com/pydata/xarray@main#egg=xarray > ci/extra_requirements.txt

    - name: Install using PyPI
      uses: Unidata/MetPy/.github/actions/install-pypi@main
      with:
        need-extras: true
        type: test
        version-file: Prerelease
        python-version: 3.12
        need-cartopy: 'false'

    - name: Run tests
      id: tests
      uses: Unidata/MetPy/.github/actions/run-tests@main
      with:
        run-doctests: false
        key: nightly
        upload-coverage: false
        pytest-args: ''

    - name: Upload test log
      if: failure()
      uses: actions/upload-artifact@v5
      with:
        name: log-nightly-tests
        path: tests-nightly.log
        retention-days: 5

  Docs:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.build.outcome }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v5
      with:
        fetch-depth: 150
        fetch-tags: true

    - name: Assemble doc requirements
      run: |
        echo git+https://github.com/pydata/xarray@main#egg=xarray > ci/extra_requirements.txt

    - name: Install using PyPI
      uses: Unidata/MetPy/.github/actions/install-pypi@main
      with:
        type: doc
        version-file: Prerelease
        python-version: 3.12

    - name: Build docs
      id: build
      uses: Unidata/MetPY/.github/actions/build-docs@main
      with:
        run-linkchecker: true
        key: nightly
        make-targets: ''

    - name: Upload build log
      if: failure()
      uses: actions/upload-artifact@v5
      with:
        name: log-nightly-docs
        path: |
          build.log
          linkchecker.log
        retention-days: 5
